print("Welcome to the Interactive Personal Data Collector!")
print("--------------------------------------------")
name = input("Enter your name: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height in meters: "))
weight = float(input("Enter your weight in kg: "))
fav_number = int(input("Enter your favourite number: "))
city = input("Enter your city: ")
current_year = 2026
birth_year = current_year - age
print("----- User Information -----")
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Weight:", weight)
print("Favourite Number:", fav_number)
print("City:", city)
print("----- Data Types and Memory Address -----")
print("Name -> Type:", type(name), "Memory Address:", id(name))
print("Age -> Type:", type(age), "Memory Address:", id(age))
print("Height -> Type:", type(height), "Memory Address:", id(height))
print("Weight -> Type:", type(weight), "Memory Address:", id(weight))
print("Favourite Number -> Type:", type(fav_number), "Memory Address:", id(fav_number))
print("City -> Type:", type(city), "Memory Address:", id(city))
print("Your approximate birth year is:", birth_year)
print("Thank you for using the Personal Data Collector!")
print("Keep learning Python!")