print("Personal Data Collector")
name = input("Enter your name: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height in cm: "))
weight = float(input("Enter your weight in kg: "))
city = input("Enter your city: ")
fav = int(input("Enter your favourite number: "))
year = 2026 - age
print("User Details")
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Weight:", weight)
print("City:", city)
print("Favourite Number:", fav)
print("Type and Memory Address")
print(type(name), id(name))
print(type(age), id(age))
print(type(height), id(height))
print(type(weight), id(weight))
print(type(city), id(city))
print(type(fav), id(fav))
print("Approx Birth Year:", year)
