print("Welcome to the Interactive Personal Data Collector")
name = input("Enter your name: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height in cm: "))
weight = float(input("Enter your weight in kg: "))
city = input("Enter your city: ")
phone_no = int(input("Enter your phone number:"))
fav = int(input("Enter your favorite number:"))
Birth_year = 2026 - age
print("Thank you! Here is the information we collected:")
print("User Details")
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Weight:", weight)
print("City:", city)
print("phone number:", phone_no)
print("favorite number:",fav)
print("Type and Memory Address")
print(type(name), id(name))
print(type(age), id(age))
print(type(height), id(height))
print(type(weight), id(weight))
print(type(city), id(city))
print(type(phone_no), id(phone_no))
print(type(fav),id(fav))
print("Approx Birth Year:", Birth_year)
